parameters:
#    l3_e_consolidados.example.class: L3E\ConsolidadosBundle\Example

services:
#    l3_e_consolidados.example:
#        class: %l3_e_consolidados.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
